### ISSUE TITLE
Access to container registry (FH Dortmund)?

### ISSUE THREAD

**Issue by lhake17** [UMEssen/DeidentiFHIR-Pipeline#6]
## Zugriff auf container als externe

**In Absprache mit Philipp Winnekens wollen wir von der FH Dortmund den Deidentifhir für das Remedi:Blut Projekt verwenden.**

Leider haben wir kein Zugriff auf das Github Container Registry, da es privat ist ( ghcr.io/umessen/deidentifhir-pipeline:latest )
Auf das Maven Paket haben wir auch keinen (https://maven.pkg.github.com/UMEssen/*/de/ume/deidentifhir/0.2.9/deidentifhir-0.2.9.pom )

**Können wir da Zugang bekommen oder gibt es vielleicht ein öffentliches Image?**

Danke

**Comment by UMEihle** [comment]
Entschuldigt, habe das Issue jetzt erst gesehen... Die Registry ist zur Zeit noch privat. Die jar kann aber über "Releases" runtergeladen werden: https://github.com/UMEssen/DeidentiFHIR-Pipeline/releases 
Die deidentifhir Dateien sollten auch öffentlich zugänglich sein: https://github.com/UMEssen/DeidentiFHIR/packages/1142034

**Comment by UMEihle** [comment]
Wenn ihr die jar lokal bei euch bauen wollt, bitte diese Anleitung beachten: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry 

Konkret müsst ihr in eurer .m2/settings.xml folgendes hinzufügen: 
```
<server>
      <id>github-ume</id>
      <username>insert-github-username-here</username>
      <password>insert-token-here</password>
</server>
```
Die `server.id` ist in der `pom.xml` angegeben und wird somit beim Bauen genutzt. 
Als Berechtigungen des Github classic tokens ist nur `read:packages` notwendig.

**Comment by lhake17** [comment]
Alles klar, danke.
ich werde mir das mal anschauen und versuchen das lokal zu testen, damit ich die Pipeline etwas besser nachvollziehen kann. Es kann gut sein, dass ich mich nochmal melde, falls es nicht klappt und ich da Hilfe brauche
